--TEST--
php_stream_input_seek() with PUT data
--PUT--
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi congue non erat in tincidunt. Cras ac facilisis enim. Vivamus non ullamcorper nunc. Vivamus hendrerit tellus ac nisi hendrerit viverra. Phasellus bibendum maximus eros, a aliquam orci interdum varius. Maecenas non leo arcu. Sed porttitor pulvinar ligula sed pellentesque. Quisque sagittis a velit eu ultrices. Pellentesque a dolor nunc. Ut id leo congue enim interdum semper.

Nunc metus tortor, ultrices ac turpis at, finibus pretium magna. Nulla tortor odio, posuere quis magna in, congue tincidunt felis. Proin vitae elit est. Aenean cursus egestas quam eu egestas. Sed ut tempus felis. Nulla consectetur dui eget sem congue, in eleifend purus elementum. Praesent ultrices, lacus nec pharetra vulputate, sem nisi luctus mauris, a fringilla ligula sapien non ante. Maecenas felis justo, ullamcorper nec dolor eu, aliquam facilisis neque. Nulla egestas sagittis laoreet. Quisque viverra dui egestas, maximus urna id, auctor elit. Mauris vestibulum nec massa et tristique. Nunc vel eleifend enim, quis tincidunt quam. Curabitur hendrerit, magna sit amet scelerisque luctus, tortor augue placerat velit, non convallis orci nibh quis ipsum.

Phasellus vehicula fringilla lorem. Nulla vulputate massa ac neque iaculis elementum. Etiam sed libero posuere velit vehicula maximus. Vivamus dui erat, lobortis et elit sit amet, consequat lobortis mi. Aenean finibus lectus ac tortor malesuada auctor. Phasellus gravida nulla a gravida dignissim. Nullam eget aliquam eros. Praesent ut pellentesque lectus. Nulla facilisi. Nam volutpat purus a vehicula placerat. Nunc vulputate in metus eget tempus. Phasellus ut commodo nulla. Pellentesque finibus est vitae neque egestas molestie. Ut dignissim, lorem ac ullamcorper commodo, elit diam suscipit sem, vitae posuere arcu diam id enim. Ut id commodo arcu. Fusce bibendum nibh vitae leo posuere aliquet.

Donec ac ipsum venenatis, luctus nunc sit amet, consequat nulla. Donec tincidunt nisi felis, sit amet pretium sem faucibus eget. Sed quis posuere dui. Integer blandit massa nulla, luctus porta mauris fermentum in. Donec sollicitudin commodo erat. Nam rhoncus mollis rutrum. Phasellus efficitur hendrerit pretium. Nullam dictum dui enim, molestie dictum felis egestas eget. Quisque facilisis elit mattis lacus egestas maximus. Sed vulputate ante sed est consequat pretium. Quisque fermentum elit quis lorem luctus, sed commodo purus tristique. Vivamus sit amet finibus ligula. Fusce pretium nibh vel magna bibendum, tempor luctus erat consequat. Etiam tempor risus non ipsum condimentum, a bibendum ipsum iaculis.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam at mi efficitur, dignissim ipsum vitae, sagittis lorem. Fusce bibendum facilisis mattis. Vivamus dignissim pretium lacus, nec accumsan libero tempus vel. Proin venenatis dignissim dolor. Proin id nibh sed justo lacinia tincidunt eget ut lorem. Proin eget purus tincidunt ante congue consequat ac tempus arcu. Vivamus est ligula, mattis eu leo in, eleifend gravida erat. Praesent sit amet fermentum mi. Curabitur nec ante sed augue malesuada pulvinar. Vestibulum scelerisque, diam et fermentum egestas, tellus ipsum hendrerit mi, in vehicula erat nisi sagittis lacus.

Praesent arcu turpis, tempus ac nunc quis, maximus ultrices nulla. Aenean hendrerit blandit nunc et ullamcorper. Vestibulum nec tellus ac orci malesuada placerat eu nec dolor. Ut ante sapien, ullamcorper faucibus condimentum quis, dictum quis lectus. Etiam convallis faucibus sem, ac auctor libero vehicula eu. Proin laoreet mi a dapibus pharetra. Vestibulum cursus tellus ex, sit amet dignissim est porttitor in.

Aliquam ante enim, malesuada suscipit justo vel, tristique accumsan turpis. Donec gravida turpis eget eros blandit, vitae vulputate tellus fermentum. Aliquam mi ligula, rutrum eu tincidunt vel, luctus sit amet nisi. Nam congue massa quis tempus mollis. Pellentesque egestas lectus eget libero pretium, nec tempor neque molestie. Nam molestie feugiat neque non mattis. Mauris posuere cursus sollicitudin.

Aenean auctor in lorem sit amet eleifend. Nulla facilisi. Maecenas pretium ullamcorper orci in interdum. Vestibulum dignissim urna nunc, id feugiat urna rutrum ac. Proin rhoncus nisl sit amet nibh efficitur cursus. In consequat nisl at tortor cursus porttitor. Duis sed congue augue. Maecenas efficitur suscipit dapibus. In nisl lacus, viverra finibus massa a, vehicula fringilla nulla. Integer malesuada elit sed enim tincidunt venenatis. Pellentesque dignissim lorem quis risus consectetur, ut lacinia risus tristique.

Maecenas iaculis urna leo, in posuere diam mollis vitae. Curabitur hendrerit felis sit amet tincidunt finibus. Proin bibendum, massa quis ornare dictum, quam risus blandit elit, non mattis lacus leo ultricies leo. Donec nec purus placerat, semper orci id, convallis urna. Vestibulum in leo lacus. Nulla scelerisque sagittis iaculis. Aliquam viverra rhoncus enim ut viverra. Sed dignissim nisl in sem convallis, a tempus massa sollicitudin.

Integer semper imperdiet turpis, bibendum sodales ex lobortis sed. In hac habitasse platea dictumst. Fusce tempus urna vitae viverra imperdiet. Pellentesque venenatis nisi erat, a molestie ex ornare a. Integer faucibus purus mauris. Maecenas tempus, ipsum eget tincidunt viverra, libero eros dapibus sapien, non tempor lectus turpis accumsan turpis. Ut non lobortis ex, at imperdiet enim. Vestibulum sagittis placerat neque vitae interdum. Praesent ut purus hendrerit, cursus tellus sit amet, fringilla libero. Donec eget facilisis nisi, eu lobortis leo. Vivamus in sodales sapien.

Praesent elementum tempus lorem, at feugiat justo tincidunt at. Nunc eu elementum nibh. Phasellus nibh nulla, placerat ut maximus id, scelerisque semper enim. Etiam sit amet feugiat quam. Duis odio tellus, mattis vitae gravida suscipit, imperdiet et ex. Nam sed turpis tempor ante porta tincidunt ut in metus. Curabitur at odio non leo faucibus tincidunt. Nam condimentum dictum rutrum. Nam semper placerat placerat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras sagittis eget dolor ut posuere. Mauris lectus diam, lobortis eget dictum vel, vehicula quis sem.

Nunc congue mollis lectus, at sagittis nibh pulvinar sed. Aliquam malesuada leo id dolor semper, a dictum lorem scelerisque. Donec dictum viverra felis, in venenatis massa placerat sed. Maecenas semper diam nulla, tincidunt finibus enim ultrices sed. Nunc mattis, nulla sed ullamcorper consectetur, diam diam cursus nulla, ac ornare velit nibh quis diam. Curabitur nec dictum lorem. Ut in mollis massa, sollicitudin scelerisque ante. Aenean nec quam malesuada nisi malesuada consequat. Nulla vestibulum rutrum orci quis ultricies.

Nulla rhoncus purus ut fermentum ullamcorper. Quisque accumsan laoreet nisl, a sagittis massa feugiat eu. Duis congue dolor sit amet nisl efficitur vulputate. Sed aliquam finibus ex. Quisque at lorem eu orci fermentum ultricies. Nulla fermentum, lorem et varius rhoncus, magna diam interdum neque, et hendrerit enim massa at ex. Praesent at tempus est. Morbi quis sagittis magna. Etiam est lacus, fringilla sed placerat ac, gravida in lacus. Curabitur vitae nisi ac velit fermentum mattis. Nam nibh turpis, egestas eget gravida vitae, faucibus ut diam.

In nunc turpis, fringilla ac eros vitae, luctus laoreet lorem. Mauris in mi non est fermentum elementum sit amet nec felis. Praesent vitae condimentum nibh. Curabitur tincidunt venenatis tellus, vitae gravida ligula imperdiet ac. Integer et ipsum ac nibh rutrum efficitur sit amet at libero. Praesent feugiat lacus sed varius sagittis. Nulla varius ipsum in felis molestie ultrices.

Morbi placerat at ex nec laoreet. Vestibulum eros nisi, bibendum quis eros lacinia, ullamcorper scelerisque mi. Ut dolor urna, hendrerit finibus metus vitae, faucibus iaculis mauris. Vestibulum rhoncus facilisis consequat. Aenean diam justo, pretium non lorem a, condimentum porttitor mi. Integer convallis cursus vehicula. Nunc blandit, diam vitae ullamcorper mollis, ex elit accumsan elit, sit amet auctor libero mi vitae dui. Nullam ultrices feugiat tempor. Suspendisse condimentum velit nec ligula porta, ac malesuada mi efficitur. Cras tempus efficitur sapien. Suspendisse eget erat est. Mauris mattis pulvinar mi, quis consectetur mauris rutrum id. Fusce consequat eros metus, id feugiat orci rhoncus a.

Sed sed placerat ex. Phasellus vehicula, ex non ultrices facilisis, eros sem interdum elit, sit amet tempor nisl risus nec ipsum. In vitae massa luctus, interdum sem vitae, efficitur nunc. Quisque commodo massa aliquam tortor hendrerit tincidunt. In rhoncus lobortis eros, non sagittis justo dignissim at. Sed lacus velit, viverra ac purus a, pellentesque egestas lorem. Cras quis est ac orci dapibus gravida. Suspendisse dapibus odio at purus porta malesuada eget ac libero. Aliquam faucibus elit quis ligula mattis auctor. Nam vitae arcu non tortor semper rutrum. Ut ac malesuada mi, ut pulvinar est. Nullam gravida nibh quis elit laoreet blandit. Etiam et condimentum mi.

Integer ultricies erat vitae ullamcorper pulvinar. Suspendisse imperdiet ipsum erat, et blandit mauris efficitur eget. Aliquam nec sapien ante. Pellentesque sagittis malesuada ipsum, at placerat nunc finibus nec. Sed tincidunt vestibulum tellus at rhoncus. Fusce nec ex mauris. Vivamus condimentum ut dui sit amet cursus. Suspendisse bibendum dolor ac mauris vehicula bibendum ut eget nunc. Phasellus ut arcu odio. Duis semper id mi vel placerat. Donec quis erat ante.

Vestibulum erat lectus, malesuada id ligula eget, dapibus lobortis eros. Morbi quis turpis volutpat nisi volutpat convallis sit amet et ex. Aenean non tincidunt lorem. Fusce quis posuere leo. Duis pretium lectus sit amet nulla scelerisque sollicitudin. In congue tellus ac velit egestas, eget egestas massa ultrices. Aenean facilisis auctor sem, nec ornare ligula efficitur eu. Maecenas at felis tincidunt, aliquam nisl et, interdum tellus. Quisque mollis risus et nunc vestibulum, id cursus dolor pharetra. Maecenas at nisl id velit laoreet tempus. Vestibulum maximus porttitor dolor, at commodo nunc blandit id. Praesent dui dolor, ornare non est eu, hendrerit tincidunt orci. Integer a elit eget nibh condimentum pellentesque ut nec eros.

Praesent suscipit dui finibus libero vehicula, vel imperdiet risus hendrerit. Vestibulum sem tortor, gravida id varius et, hendrerit eget nunc. Etiam massa augue, lobortis nec eros quis, bibendum congue diam. Nulla lobortis justo eleifend lacus semper ultricies. Donec ultricies, sem a pretium dignissim, tortor est malesuada sapien, ut sollicitudin magna mauris in dolor. Mauris ac efficitur nisi. Fusce rhoncus sodales nulla, consectetur mattis nunc. Aenean orci ipsum, mollis ut purus id, porttitor finibus metus. Maecenas commodo ligula est, ut blandit lacus hendrerit eget. Sed congue hendrerit tincidunt. Nunc mattis interdum iaculis. Donec et dictum magna, nec porttitor nunc. Pellentesque eget velit sed urna condimentum elementum. Donec condimentum rutrum libero, non fringilla tortor volutpat id.

Praesent porta sapien ante, nec tristique purus dictum vel. Morbi faucibus fermentum dolor, eu aliquet ipsum dapibus eget. Integer tincidunt, velit vel dictum ultricies, tellus dui scelerisque velit, et dignissim tortor dolor sit amet nulla. Vivamus sem purus, tincidunt sit amet mauris eu, tempor ornare dui. Sed tempus fermentum massa eget hendrerit. Sed eget quam a odio commodo porttitor. Curabitur dui felis, ullamcorper sit amet arcu id, posuere aliquet risus.

Nam sit amet ultricies leo, quis volutpat purus. Quisque vel orci iaculis tellus sollicitudin tempus. Etiam venenatis libero sed dui iaculis, nec venenatis ex efficitur. Quisque et mi lacinia, dictum nulla eu, maximus nulla. Aenean consectetur dignissim ex, nec molestie lacus porta non. Nulla mauris sapien, ullamcorper a libero sit amet, scelerisque tempus metus. In vehicula risus et purus semper, vel congue massa blandit. Donec sit amet quam odio. Ut auctor tincidunt nisl, sed sollicitudin nibh volutpat sit amet. Maecenas leo elit, vehicula at purus id, sodales malesuada dui. Cras eget suscipit elit, at consectetur dolor. Nam eu odio eget mauris imperdiet aliquet.

Aliquam eu iaculis urna. Nullam eget congue sem, sed ornare magna. Suspendisse aliquet elit erat, et luctus mi faucibus pulvinar. Ut aliquam urna at mollis iaculis. In non porttitor felis. Praesent bibendum eros elit, vitae efficitur augue ultrices ultrices. Phasellus suscipit odio et sodales ornare. Integer faucibus ipsum ut lectus aliquet, in vehicula augue faucibus. Vivamus auctor mi a commodo efficitur.

Donec fringilla vitae massa quis vulputate. Nulla porta pharetra lectus, nec finibus nunc placerat at. Praesent id neque tincidunt, tempus enim ac, scelerisque metus. Ut scelerisque enim at erat ultrices commodo. Suspendisse egestas quam ut tellus suscipit commodo. Suspendisse egestas augue tellus, ultrices sollicitudin sapien tincidunt quis. Morbi vitae massa ligula. Cras eleifend erat massa, sit amet vehicula elit tincidunt at. Maecenas velit orci, fringilla a dolor eu, semper vestibulum ante. Ut ut lacinia risus, ac tristique libero. Phasellus at sapien ligula. Quisque tristique orci id faucibus elementum. Ut sem ante, vehicula id lacinia eget, lacinia non dui. Nunc eu scelerisque sapien. Fusce tristique, elit non malesuada ultricies, justo leo ornare neque, non condimentum nulla justo eu risus.

Ut non ex felis. Curabitur malesuada tempus dolor in tincidunt. Phasellus non massa aliquet sem pharetra tincidunt. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam sit amet consequat nulla. Integer tincidunt lorem nisi. Maecenas eu lacus quam. Donec ac ornare quam, eget mollis mi. Ut ac eros nisi. Etiam maximus, orci non auctor blandit, sem est porttitor lacus, ut auctor nibh enim eget ligula. Quisque non leo a dui efficitur euismod in quis erat.

Praesent ac leo eu nulla fermentum gravida at vitae nunc. Etiam fermentum ornare orci, sit amet facilisis libero semper sit amet. Etiam interdum molestie ante, eu tempor risus lobortis sed. Cras dapibus massa et sem suscipit posuere. Mauris ullamcorper tincidunt odio, sed porttitor nunc pulvinar consequat. Proin facilisis sem vitae sem malesuada pharetra et id dolor. Vestibulum rutrum turpis vitae laoreet blandit.

Maecenas ultricies tellus volutpat fringilla consequat. Fusce elementum dui sit amet porta lobortis. Donec ut risus mattis turpis iaculis ullamcorper. Cras ullamcorper erat dui, id vestibulum tortor vestibulum ut. Mauris tempus consectetur nisi, quis lobortis nisi elementum et. Nunc blandit porta convallis. Aliquam nulla risus, egestas fermentum viverra convallis, elementum ac dui. Nam vestibulum tellus at tincidunt vestibulum. Quisque tristique lacus urna, ut auctor magna imperdiet in. Sed malesuada condimentum libero, id venenatis neque tincidunt sit amet. Vestibulum congue venenatis vehicula. In varius a odio a maximus. Donec faucibus orci vitae fermentum bibendum. Sed fermentum quam sit amet ex blandit dictum. Nam elementum ante sit amet urna efficitur vehicula.

Quisque ullamcorper quam vitae nibh scelerisque aliquam. Vestibulum maximus pellentesque condimentum. Pellentesque eget nibh sollicitudin, tristique mauris at, hendrerit magna. Curabitur hendrerit tincidunt posuere. Vestibulum vulputate aliquam justo, in aliquet ipsum maximus non. Proin porta, urna id efficitur egestas, est diam rutrum sem, non consectetur nisl lacus in nibh. Quisque nec ipsum pretium, elementum elit et, ullamcorper nibh. Nulla vitae lorem ut tortor luctus bibendum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus blandit nulla a nisi ornare, eu consectetur tortor finibus. Sed massa sem, interdum scelerisque convallis at, dapibus accumsan nisl.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel vehicula nulla. Ut id quam felis. Ut tincidunt aliquam eros, id euismod nulla interdum non. Aenean nunc lorem, tempor eu massa sed, efficitur congue mi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla pellentesque sagittis urna sit amet ullamcorper. Etiam mollis leo aliquam fermentum laoreet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras et enim et libero sollicitudin nullam.
--FILE--
<?php
$i = fopen('php://input', 'r');
fseek($i, 5);
var_dump(fread($i, 10));
fseek($i, 5);
fread($i, 2);
fseek($i, 2, SEEK_CUR);
var_dump(fread($i, 10));
rewind($i);
var_dump(fread($i, 5));
fseek($i, -6, SEEK_END);
var_dump(fread($i, 6));


?>
--EXPECT--
string(10) " ipsum dol"
string(10) "um dolor s"
string(5) "Lorem"
string(6) "ullam."
